site_name: Doing Geospatial in Python
site_description: Doing Geospatial in Python is a workshop on performing common GIS/geospatial tasks using Python geospatial tools.
site_author: the Doing Geospatial in Python Team
copyright: Copyright (c) 2019-2025 the Doing Geospatial in Python Team<br/>This website is released under the <a href="https://creativecommons.org/licenses/by/4.0">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a>
site_url: https://geopython.github.io/geopython-workshop
repo_url: https://github.com/geopython/geopython-workshop
docs_dir: docs
edit_uri: edit/master/web/docs

nav:
    - Home: index.md
    - Docker installation: docker.md

theme: 
    name: material
    icon:
        logo: material/language-python
    palette:
        # primary: light blue
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
                icon: material/brightness-7
                name: Switch to dark mode

    # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

plugins:
    - search

extra_css:
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
    - assets/javascripts/termynal.js
    - assets/javascripts/custom.js

markdown_extensions:
  - pymdownx.superfences